os: Visual Studio 2015
init:
  - ps: |
        Start-FileDownload 'http://nightlies.dlang.org/dmd-nightly/dmd.master.windows.7z' -FileName 'dmd2.7z'
        7z x dmd2.7z > $null
        Set-Item -path env:DMD -value c:\projects\dmd2\windows\bin\dmd.exe
        c:\projects\dmd2\windows\bin\dmd.exe --version

build_script:
  - cd c:\projects\modernui
  - dmd -m64 -O -w -release -c -version=Unicode -vcolumns -of"Debug\ModernUI.obj" -Idirectx-d\src source\app.d source\collections.d source\core.d source\rx.d source\ui.d